apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: podinfo-chart
spec:
  interval: 1h
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: 6.9.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  kubeConfig:
    configMapRef:
      name: ${KUBECONFIG}
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: podinfo-chart
  releaseName: podinfo
  targetNamespace: frontend
  storageNamespace: frontend
