##@ General

export CLUSTER_TOPOLOGY=true

GENERATED_BY := "\# Generated by Makefile."

HUB_NAME := "hub"
SPOKE_NAME := "spoke"

HUB_CONTEXT := "kind-hub"
CLUSTER_API := components/cluster-api/cluster-api.yaml
BOOTSTRAP_KUBEADM := components/cluster-api/bootstrap-kubeadm.yaml
CONTROL_PLANE_KUBEADM := components/cluster-api/control-plane-kubeadm.yaml
INFRASTRUCTURE_DOCKER := components/cluster-api/infrastructure-docker.yaml
SPOKE_MANIFESTS := components/spoke-cluster/spoke-cluster.yaml
SPOKE_VERSION := "v1.35.0"
SPOKE_NAMESPACE := "spoke-cluster"
SPOKE_CP_MACHINE_COUNT := 1
SPOKE_WORKER_MACHINE_COUNT := 1

CLUSTERCTL_VERSION := $(shell clusterctl version -o short | tr -d '\n')

.PHONY: bootstrap
bootstrap: ## Bootstrap all clusters.
	kind create cluster \
		--config=$(HUB_NAME).yaml
	helm install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator \
		--kube-context=$(HUB_CONTEXT) \
		--namespace=flux-system \
		--create-namespace
	kubectl config set-context $(HUB_CONTEXT) \
		--namespace=flux-system
	kubectl apply \
		--context=$(HUB_CONTEXT) \
		--filename=clusters/$(HUB_NAME)/flux-system/flux-instance.yaml
	until kind export kubeconfig --name=$(SPOKE_NAME) >/dev/null 2>&1; do \
		sleep 5; \
	done
	kubectl config use-context $(HUB_CONTEXT)

.PHONY: delete
delete: ## Delete all clusters.
	kubectl delete cluster $(SPOKE_NAME) \
		--context=$(HUB_CONTEXT) \
		--namespace=$(SPOKE_NAMESPACE)
	kubectl wait cluster $(SPOKE_NAME) \
		--context=$(HUB_CONTEXT) \
		--namespace=$(SPOKE_NAMESPACE) \
		--for=delete
	kind delete cluster \
		--name=$(HUB_NAME)

.PHONY: generate
generate: $(CLUSTER_API) $(BOOTSTRAP_KUBEADM) $(CONTROL_PLANE_KUBEADM) $(INFRASTRUCTURE_DOCKER) $(SPOKE_MANIFESTS) ## Generate/upgrade Cluster API manifests.

.PHONY: $(CLUSTER_API)
$(CLUSTER_API): ## Generate Cluster API core manifests.
	echo "$(GENERATED_BY)" > $@
	clusterctl generate provider \
		--core=cluster-api:$(CLUSTERCTL_VERSION) \
		--target-namespace=capi-system \
		>> $@

.PHONY: $(BOOTSTRAP_KUBEADM)
$(BOOTSTRAP_KUBEADM): ## Generate Cluster API bootstrap provider manifests.
	echo "$(GENERATED_BY)" > $@
	clusterctl generate provider \
		--bootstrap=kubeadm:$(CLUSTERCTL_VERSION) \
		--target-namespace=capi-kubeadm-bootstrap-system \
		>> $@

.PHONY: $(CONTROL_PLANE_KUBEADM)
$(CONTROL_PLANE_KUBEADM): ## Generate Cluster API control plane provider manifests.
	echo "$(GENERATED_BY)" > $@
	clusterctl generate provider \
		--control-plane=kubeadm:$(CLUSTERCTL_VERSION) \
		--target-namespace=capi-kubeadm-control-plane-system \
		>> $@

.PHONY: $(INFRASTRUCTURE_DOCKER)
$(INFRASTRUCTURE_DOCKER): ## Generate Cluster API infrastructure provider manifests.
	echo "$(GENERATED_BY)" > $@
	clusterctl generate provider \
		--infrastructure=docker:$(CLUSTERCTL_VERSION) \
		--target-namespace=capd-system \
		>> $@

.PHONY: $(SPOKE_MANIFESTS)
$(SPOKE_MANIFESTS): ## Generate Cluster API manifests for spoke cluster.
	echo "$(GENERATED_BY)" > $(SPOKE_MANIFESTS)
	kubectl create namespace $(SPOKE_NAMESPACE) \
		--dry-run=client \
		-o yaml | yq 'del(.spec, .status)' \
		>> $(SPOKE_MANIFESTS)
	echo "---" >> $(SPOKE_MANIFESTS)
	clusterctl generate cluster $(SPOKE_NAME) \
		--flavor=development \
		--infrastructure=docker:$(CLUSTERCTL_VERSION) \
		--kubernetes-version=$(SPOKE_VERSION) \
		--control-plane-machine-count=$(SPOKE_CP_MACHINE_COUNT) \
		--worker-machine-count=$(SPOKE_WORKER_MACHINE_COUNT) \
		--target-namespace=$(SPOKE_NAMESPACE) \
		>> $(SPOKE_MANIFESTS)

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
