apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-api
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h
  retryInterval: 1m
  path: components/cluster-api
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
