apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: tenants
  namespace: spoke-cluster
spec:
  dependsOn:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tenants-rbac
      namespace: spoke-cluster
      ready: true
  inputs:
    - tenant: backend
    - tenant: frontend
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.tenant >>
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: admin
        namespace: << inputs.tenant >>
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: spoke-cluster-kubeconfig
        namespace: << inputs.tenant >>
        labels:
          reconcile.fluxcd.io/watch: Enabled
        annotations:
          fluxcd.controlplane.io/convertKubeConfigFrom: spoke-cluster/spoke-kubeconfig
      data:
        provider: generic
        audiences: spoke-cluster
        serviceAccountName: admin
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: spoke-cluster
        namespace: << inputs.tenant >>
      spec:
        namePrefix: spoke-cluster-
        targetNamespace: << inputs.tenant >>
        interval: 1h
        retryInterval: 1m
        path: tenants/<< inputs.tenant >>
        prune: true
        wait: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        postBuild:
          substitute:
            KUBECONFIG: spoke-cluster-kubeconfig
